const stamp = '2025-04-12T08:30:00.000Z';

export const sifiaThought = { id: 'thought-1', server_id: 'server-thought-1', user_id: 'user-1', title: 'A thought', content: 'Grace met me here.', type: 'thoughts', source: 'thoughts', selected_date: '2025-04-12', created_at: stamp, updated_at: stamp };
export const sifiaGuided = { id: 'guided-1', server_id: 'server-guided-1', user_id: 'user-1', title: 'Guided', content: 'I can release this fear.', type: 'guided', source: 'guided', prompt: 'What are you carrying?', selected_date: '2025-04-12', created_at: stamp, updated_at: stamp };
export const devotionalPonder = { id: 'devo-ponder-1', server_id: 'server-devo-ponder-1', user_id: 'user-1', title: 'Ponder', content: 'I will wait with hope.', type: 'devotional', source: 'devotional', prompt: 'Where can you practice hope?', question_text: 'Where can you practice hope?', devotional_id: 'devotional-1', devotional_title: 'Hope in Waiting', day_number: 2, day_title: 'Remain', total_days: 3, question_number: 1, selected_date: '2025-04-12', created_at: stamp, updated_at: stamp };
export const devotionalReflection = { ...devotionalPonder, id: 'devo-reflection-1', server_id: 'server-devo-reflection-1', title: 'Devotional Reflection', content: 'God was present in the delay.', prompt: undefined, question_text: undefined, question_number: undefined };
export const playbookReflection = { id: 'playbook-reflection-1', server_id: 'server-playbook-reflection-1', user_id: 'user-1', title: 'Reflection', content: 'I will make the call today.', type: 'playbook', source: 'playbook', prompt: 'What is your next faithful step?', playbook_id: 'playbook-1', playbook_title: 'Courage for Today', subtask_id: 'subtask-1', selected_date: '2025-04-12', created_at: stamp, updated_at: stamp };
export const faithfulAction = { id: 'action-step-1', playbook_id: 'playbook-1', text: 'Make the call', description: 'Reach out before noon.', completed: false, order_index: 0, created_at: stamp, updated_at: stamp };
export const devotionalPrayer = { id: 'devotional-prayer-1', server_id: 'server-devotional-prayer-1', prayer_type: 'devotional', source: 'devotional', content: 'Help me wait with hope.', devotional_title: 'Hope in Waiting', day_number: 2, day_title: 'Remain', selected_date: '2025-04-12', created_at: stamp, updated_at: stamp, metadata: { devotional_id: 'devotional-1' } };
export const playbookPrayer = { id: 'playbook-prayer-1', server_id: 'server-playbook-prayer-1', prayer_type: 'guided_playbook', source: 'playbook', content: 'Give me courage to act.', selected_date: '2025-04-12', created_at: stamp, updated_at: stamp, metadata: { playbook_id: 'playbook-1', playbook_title: 'Courage for Today', step_id: 'action-step-1', subtask_id: 'subtask-1', prompt: 'Pray before acting.' } };
export const sharedTimeBlock = { id: 'time-block-1', user_id: 'user-1', selected_date: '2025-04-12', start_time: '2025-04-12T09:00:00', end_time: '2025-04-12T10:00:00', all_day: false, title: 'Quiet time', category: 'faith', version: 2, created_at: stamp, updated_at: stamp };
