-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgxEleI8vMybVfyXZN
/GPcAQjfYJFatYNxVHxvieMeMz+gCgYIKoZIzj0DAQehRANCAARxHsmStTYFkNJf
skjqS4z3Le+vGoeKbgQ6U8Nk5mkDJF8WQkMrlyE2yLlvulSlMqr3DXihfpBDdoqi
o9dd4B6K
-----END PRIVATE KEY-----