
auth.token=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

defaults.org=sifia
defaults.project=react-native

defaults.url=https://sentry.io/
