export const CURATED_GUIDED_QUESTIONS = [
  {topic: 'With God', prompt: 'Am I prioritizing daily prayer and Scripture reading?'},
  {topic: 'With God', prompt: 'Am I serving others in my church or community?'},
  {topic: 'With God', prompt: 'Where have I noticed God at work in my life lately?'},
  {topic: 'With God', prompt: 'What am I finding difficult to trust God with right now?'},
  {topic: 'With God', prompt: 'What truth from Scripture do I need to remember today?'},
  {topic: 'My Heart', prompt: 'What challenged my faith, and how did I respond?'},
  {topic: 'My Heart', prompt: 'How am I managing stress to protect my mental health?'},
  {topic: 'My Heart', prompt: 'Am I allowing comparison to steal my joy and gratitude for what God has given me?'},
  {topic: 'My Heart', prompt: 'What emotion have I been avoiding, and what might it be showing me?'},
  {topic: 'My Heart', prompt: 'What do I need to receive, release, or bring honestly before God?'},
  {topic: 'Relationships', prompt: "Did I reflect Christ's love in my interactions?"},
  {topic: 'Relationships', prompt: 'Did I show forgiveness or grace to someone today?'},
  {topic: 'Relationships', prompt: "Am I encouraging others' faith or well-being this week?"},
  {topic: 'Relationships', prompt: 'Is there a conversation I need to begin with honesty and kindness?'},
  {topic: 'Relationships', prompt: 'Who might need my presence more than my advice right now?'},
  {topic: 'Decisions', prompt: "How did I seek God's guidance in my decisions today?"},
  {topic: 'Decisions', prompt: 'What decision is taking up the most space in my mind?'},
  {topic: 'Decisions', prompt: 'What facts, wise counsel, or prayer do I still need before deciding?'},
  {topic: 'Decisions', prompt: 'Am I being led by faith, fear, pressure, or peace?'},
  {topic: 'Decisions', prompt: 'What is the next faithful step, even if I cannot see the whole path?'},
  {topic: 'Growth', prompt: 'What habit or sin is hindering me, and how can I address it?'},
  {topic: 'Growth', prompt: "What's one step I can take to improve my physical health?"},
  {topic: 'Growth', prompt: "What's one way I can grow in a practical skill to reflect God's excellence?"},
  {topic: 'Growth', prompt: 'What pattern keeps showing up, and what might it be teaching me?'},
  {topic: 'Growth', prompt: 'Where can I see quiet progress that I have overlooked?'},
  {topic: 'Work & Gifts', prompt: "How am I using my talents and resources for God's glory?"},
  {topic: 'Work & Gifts', prompt: "Is my career or business aligned with God's values?"},
  {topic: 'Work & Gifts', prompt: 'How can I pursue excellence in my work to honor God?'},
  {topic: 'Work & Gifts', prompt: 'Which gift have I been hesitant to use, and why?'},
  {topic: 'Work & Gifts', prompt: 'What would faithful work look like today, apart from recognition or results?'},
  {topic: 'Finances', prompt: 'Am I trusting God with my work or financial concerns?'},
  {topic: 'Finances', prompt: 'What story am I telling myself about money, security, or enough?'},
  {topic: 'Finances', prompt: 'Does the way I spend reflect what I say matters most?'},
  {topic: 'Finances', prompt: 'Where could I practice greater wisdom, contentment, or generosity?'},
  {topic: 'Finances', prompt: 'What financial responsibility needs my calm and honest attention?'},
  {topic: 'Business', prompt: 'Does the way I lead my business reflect integrity, service, and stewardship?'},
  {topic: 'Business', prompt: 'What business decision needs prayer, better information, or wise counsel?'},
  {topic: 'Business', prompt: 'Am I measuring success in a way that supports the life and values I want to keep?'},
  {topic: 'Business', prompt: 'Who is affected by my next business decision, and what do I owe them?'},
  {topic: 'Business', prompt: 'What is the most faithful priority for my business in this season?'},
  {topic: 'Home', prompt: 'What would make my home feel more peaceful and life-giving this week?'},
  {topic: 'Home', prompt: 'Is there something at home that needs care, repair, or simplification?'},
  {topic: 'Home', prompt: 'What atmosphere am I helping create for the people who share my home?'},
  {topic: 'Home', prompt: 'What household responsibility have I been avoiding?'},
  {topic: 'Home', prompt: 'Where can I choose welcome and presence over perfection at home?'},
  {topic: 'Family', prompt: 'Who in my family needs intentional time or encouragement from me?'},
  {topic: 'Family', prompt: 'What family rhythm is helping us, and what rhythm needs to change?'},
  {topic: 'Family', prompt: 'Is there a family tension I need to approach with grace and truth?'},
  {topic: 'Family', prompt: 'What do I want the people closest to me to feel when they are with me?'},
  {topic: 'Family', prompt: 'What family moment from this season do I want to remember?'},
  {topic: 'Health', prompt: 'What is my body asking me to notice today?'},
  {topic: 'Health', prompt: 'Which small choice would support my physical or emotional well-being?'},
  {topic: 'Health', prompt: 'Am I treating my limits as wisdom or as an inconvenience?'},
  {topic: 'Health', prompt: 'What support, care, or professional help have I been postponing?'},
  {topic: 'Health', prompt: 'How can I care for my health without being ruled by fear or perfection?'},
  {topic: 'Rest & Rhythms', prompt: 'Where do I need permission to pause?'},
  {topic: 'Rest & Rhythms', prompt: 'What has been draining me, and what has been restoring me?'},
  {topic: 'Rest & Rhythms', prompt: 'Which daily or weekly rhythm helps me stay grounded with God?'},
  {topic: 'Rest & Rhythms', prompt: 'What can I let go of to make room for what matters in this season?'},
  {topic: 'Rest & Rhythms', prompt: 'What would meaningful rest look like for me this week?'},
] as const;

export const GUIDED_PROMPTS: string[] = CURATED_GUIDED_QUESTIONS.map(item => item.prompt);

export type ViewMode = 'free-form' | 'guided';
