import type { LocalPrayerEntry } from '../storage/prayerStorage';

export const PRAYER_V2_DEMO_PREFIX = 'dev-prayer-v2-';
export const PRAYER_V2_DEMO_NEED_PREFIX = 'dev-need-v2-';
export const PRAYER_V2_DEMO_NEED_TOPICS = ['Provision', 'School', 'Relationships', 'Work & business', 'Health', 'Guidance', 'Other'] as const;
export type PrayerV2DemoScenario = 'full' | 'return' | 'check_in' | 'follow_up' | 'remember' | 'celebrate' | 'mixed_needs' | 'review' | 'cast';

export interface PrayerV2DemoFixture extends LocalPrayerEntry {
  demoLabel: string;
  expectedToday?: 'return' | 'check_in' | 'follow_up' | 'remember' | 'celebrate' | 'none';
  expectedReview: string;
}

const DAY = 86_400_000;
const atNoon = (date: Date) => { const copy = new Date(date); copy.setHours(12, 0, 0, 0); return copy; };
const daysAgo = (reference: Date, days: number) => new Date(atNoon(reference).getTime() - days * DAY);
const monthsAgo = (reference: Date, months: number) => { const date = atNoon(reference); date.setMonth(date.getMonth() - months); return date; };
const iso = (date: Date) => date.toISOString();
const ymd = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const id = (name: string) => `${PRAYER_V2_DEMO_PREFIX}${name}`;
const needId = (name: string) => `${PRAYER_V2_DEMO_NEED_PREFIX}${name}`;

type Seed = Omit<PrayerV2DemoFixture, 'created_at' | 'updated_at' | 'selected_date' | 'version' | 'sync_status' | 'deleted'> & {
  createdDaysAgo?: number; createdMonthsAgo?: number; updatedDaysAgo?: number;
};

export function buildPrayerV2DemoFixtures(referenceDate: Date): PrayerV2DemoFixture[] {
  const make = (seed: Seed): PrayerV2DemoFixture => {
    const created = seed.createdMonthsAgo !== undefined ? monthsAgo(referenceDate, seed.createdMonthsAgo) : daysAgo(referenceDate, seed.createdDaysAgo || 0);
    const updated = daysAgo(referenceDate, seed.updatedDaysAgo ?? seed.createdDaysAgo ?? 0);
    const { createdDaysAgo: _days, createdMonthsAgo: _months, updatedDaysAgo: _updated, ...entry } = seed;
    return { ...entry, selected_date: ymd(created), created_at: iso(created), updated_at: iso(updated), version: 1, sync_status: 'local', deleted: false };
  };
  const active = { track_answered: true, is_active: true, tracking_status: 'pending' };
  const answer = (name: string, days: number, note: string) => ({ id: `${id(name)}-answer`, date: iso(daysAgo(referenceDate, days)), note });
  const lifecycle = (name: string, days: number, action: 'let-go' | 'return') => ({ id: `${id(name)}-${action}`, date: iso(daysAgo(referenceDate, days)), action });
  const need = (name: string, topic: string, text: string, state: 'active' | 'answered' | 'closed', days = 9) => ({
    id: needId(name), topic, text, status: state === 'active' ? 'pending' : state, active: state === 'active',
    ...(state === 'answered' ? { answeredDate: iso(daysAgo(referenceDate, days)), answerHistory: [{ id: `${needId(name)}-answer`, date: iso(daysAgo(referenceDate, days)), note: `I recorded a meaningful update for “${text}”.` }] } : {}),
    ...(state === 'closed' ? { closedByParent: false, lifecycleHistory: [{ id: `${needId(name)}-let-go`, date: iso(daysAgo(referenceDate, days)), action: 'let-go' as const, needId: needId(name), note: 'This specific concern is no longer something I am actively carrying.' }] } : {}),
  });

  return [
    make({ id: id('recent-active'), demoLabel: 'Recent active prayer', expectedToday: 'none', expectedReview: 'New in prayer', content: 'Lord, give me peace before an upcoming conversation.', prayer_type: 'journal', journal_category: 'supplication', prayed: true, prayer_count: 2, last_prayed_at: iso(daysAgo(referenceDate, 1)), status: 'pending', metadata: active, createdDaysAgo: 2, updatedDaysAgo: 1 }),
    make({ id: id('return'), demoLabel: 'Return — work transition', expectedToday: 'return', expectedReview: 'Still carrying', content: "Heavenly Father,\n\nI have been carrying this decision in my mind for days. Please help me stop trying to force clarity before it is time. Give me wisdom to recognize what is mine to do today and patience with what I cannot resolve yet. Keep fear from making the decision for me, and help me obey You one step at a time.\n\nIn Jesus' name, amen.", prayer_type: 'journal', journal_category: 'personal_prayer', prayed: true, prayer_count: 7, last_prayed_at: iso(daysAgo(referenceDate, 18)), status: 'pending', metadata: { ...active, prayer_style: 'open' }, createdDaysAgo: 80, updatedDaysAgo: 18 }),
    make({ id: id('check-in'), demoLabel: 'Check In — serving decision', expectedToday: 'check_in', expectedReview: 'Still carrying', content: "Dear Lord,\n\nPlease give me wisdom as I think about where I should serve in this season. Help me distinguish between saying yes because I am afraid to disappoint people and saying yes because it is actually where You are leading me. Give me humility to listen, courage to say no when needed, and willingness to serve faithfully where I should.\n\nIn Jesus' name, amen.", prayer_type: 'journal', journal_category: 'personal_prayer', prayed: true, prayer_count: 3, last_prayed_at: iso(daysAgo(referenceDate, 7)), status: 'pending', metadata: { ...active, prayer_style: 'open' }, createdMonthsAgo: 8, updatedDaysAgo: 7 }),
    make({ id: id('old-recent'), demoLabel: 'Old but prayed yesterday', expectedToday: 'none', expectedReview: 'Still carrying only when selected', content: 'Keep shaping patience and kindness in me.', prayer_type: 'journal', journal_category: 'supplication', prayed: true, prayer_count: 12, last_prayed_at: iso(daysAgo(referenceDate, 1)), status: 'pending', metadata: active, createdMonthsAgo: 10, updatedDaysAgo: 1 }),
    make({ id: id('remember'), demoLabel: 'Remember — project provision', expectedToday: 'remember', expectedReview: 'Historical new prayer only in creation period', content: "Dear Lord,\n\nI want to place this season before You. I don't know yet what it means or where it is going, but I want to remember how I felt today and trust You with what comes next.\n\nIn Jesus' name, amen.", prayer_type: 'journal', journal_category: 'personal_prayer', prayed: false, prayer_count: 0, status: 'pending', metadata: { prayer_style: 'open', track_answered: false, is_active: false }, createdDaysAgo: 47, updatedDaysAgo: 47 }),
    make({ id: id('one-answer'), demoLabel: 'Celebrate — one recorded answer', expectedToday: 'celebrate', expectedReview: 'Answer event', content: "Heavenly Father,\n\nPlease provide the right opportunity and give me patience while I wait. Keep me from forcing a door simply because I am afraid nothing else will come. Give me wisdom to recognize the right opportunity when it comes and peace while I wait.\n\nIn Jesus' name, amen.", prayer_type: 'journal', journal_category: 'personal_prayer', prayed: true, prayer_count: 4, last_prayed_at: iso(daysAgo(referenceDate, 9)), status: 'answered', answered_date: iso(daysAgo(referenceDate, 8)), metadata: { prayer_style: 'open', track_answered: true, is_active: false, tracking_status: 'answered', answer_history: [answer('one-answer', 8, 'I received the offer for the role I had been praying about.')], prayer_updates: [] }, createdDaysAgo: 65, updatedDaysAgo: 8 }),
    make({ id: id('answered-active'), demoLabel: 'Answered and still praying', expectedToday: 'return', expectedReview: 'Answer event and carry-forward', content: 'Continue providing wisdom for the next stages of this decision.', prayer_type: 'journal', journal_category: 'supplication', prayed: true, prayer_count: 6, last_prayed_at: iso(daysAgo(referenceDate, 13)), status: 'answered', answered_date: iso(daysAgo(referenceDate, 23)), metadata: { ...active, answer_history: [answer('answered-active', 23, 'The first decision became clear.')] }, createdMonthsAgo: 4, updatedDaysAgo: 13 }),
    make({ id: id('multiple-answers'), demoLabel: 'Multiple answers across the year', expectedToday: 'celebrate', expectedReview: 'Separate answer events in separate periods', content: 'Guide each stage of a fictional work opportunity.', prayer_type: 'journal', journal_category: 'supplication', prayed: true, prayer_count: 8, last_prayed_at: iso(daysAgo(referenceDate, 11)), status: 'answered', answered_date: iso(monthsAgo(referenceDate, 5)), metadata: { ...active, answer_history: [{ id: `${id('multiple-answers')}-a1`, date: iso(monthsAgo(referenceDate, 5)), note: 'An initial conversation opened.' }, answer('multiple-answers-a2', 18, 'A clear next step followed.') ] }, createdMonthsAgo: 8, updatedDaysAgo: 11 }),
    make({ id: id('mixed-needs'), demoLabel: 'Mixed Prayer Needs', expectedToday: 'return', expectedReview: 'Answered Need plus Still Carrying and Let Go', content: "Heavenly Father, I pray for Greg during this season of treatment. Please give him strength physically and emotionally, give wisdom to everyone caring for him, and help his family trust You one day at a time.\n\nIn Jesus' name, amen.", prayer_type: 'people', person_name: 'Greg', prayed: true, prayer_count: 5, last_prayed_at: iso(daysAgo(referenceDate, 10)), status: 'answered', metadata: { ...active, prayer_need: true, topics: ['Health'], need_last_prayed: { [needId('travel')]: iso(daysAgo(referenceDate, 3)), [needId('strength')]: iso(daysAgo(referenceDate, 26)) }, prayer_needs: [
      { id: needId('safe-arrival'), topic: 'Health', text: 'Successful operation with no complications', status: 'answered', active: false, answeredDate: iso(daysAgo(referenceDate, 16)), answerHistory: [{ id: `${needId('safe-arrival')}-a1`, date: iso(daysAgo(referenceDate, 16)), note: 'The operation went well, and the doctors were pleased with the procedure.' }] },
      { id: needId('strength'), topic: 'Health', text: 'Strength and steady recovery during the next few weeks', status: 'pending', active: true },
      { id: needId('travel'), topic: 'Health', text: 'An earlier treatment option that is no longer being considered', status: 'closed', active: false, closedByParent: false, lifecycleHistory: [{ id: `${needId('travel')}-let-go`, date: iso(daysAgo(referenceDate, 12)), action: 'let-go', needId: needId('travel'), note: 'The care plan changed, so this option is no longer something I am actively carrying.' }] },
    ] }, createdMonthsAgo: 3, updatedDaysAgo: 10 }),
    make({ id: id('request-unprayed'), demoLabel: 'Unprayed Prayer Request', expectedToday: 'follow_up', expectedReview: 'Request received', content: 'Please pray for confidence in a fictional interview.', prayer_type: 'people', person_name: 'Jordan', is_prayer_request: true, requested_by: 'Jordan', prayed: false, prayer_count: 0, status: 'pending', metadata: active, createdDaysAgo: 6, updatedDaysAgo: 6 }),
    make({ id: id('request-prayed'), demoLabel: 'Prayed-for Request', expectedToday: 'none', expectedReview: 'Original request journey context', content: "Please pray for me. I need to talk with my dad about something we've been avoiding for a long time, and I don't want the conversation to turn into another argument.", prayer_type: 'people', person_name: 'Ben', is_prayer_request: true, requested_by: 'Ben', prayed: true, prayer_count: 1, status: 'pending', metadata: active, createdDaysAgo: 35, updatedDaysAgo: 35 }),
    make({ id: id('request-prayed-response'), demoLabel: 'Response to prayed-for Request', expectedToday: 'follow_up', expectedReview: 'Request prayed for', content: "Dear Lord, I pray for Ben as he prepares to talk with his dad. Give him wisdom to know what to say and humility to listen well. Guard both of them from anger and defensiveness. Help them speak honestly without trying to hurt one another, and give them patience if everything cannot be resolved in one conversation.\n\nIn Jesus' name, amen.", prayer_type: 'people', person_name: 'Ben', prayed: true, prayer_count: 2, last_prayed_at: iso(daysAgo(referenceDate, 19)), status: 'pending', metadata: { ...active, original_request_id: id('request-prayed'), original_request_content: "Please pray for me. I need to talk with my dad about something we've been avoiding for a long time, and I don't want the conversation to turn into another argument.", prayer_request_display: "Please pray for me. I need to talk with my dad about something we've been avoiding for a long time, and I don't want the conversation to turn into another argument." }, createdDaysAgo: 22, updatedDaysAgo: 19 }),
    make({ id: id('request-recent'), demoLabel: 'Request with recent follow-up', expectedToday: 'none', expectedReview: 'Recent request update', content: 'Please pray for encouragement before a presentation.', prayer_type: 'people', person_name: 'Riley', is_prayer_request: true, requested_by: 'Riley', prayed: true, prayer_count: 1, status: 'pending', metadata: active, createdDaysAgo: 28, updatedDaysAgo: 28 }),
    make({ id: id('request-recent-response'), demoLabel: 'Recently followed-up response', expectedToday: 'none', expectedReview: 'Recent meaningful update', content: "Father, I pray for Riley before the presentation. Settle the anxiety that makes it difficult to think clearly, help Riley explain the work with confidence and humility, and give wisdom when unexpected questions come.\n\nIn Jesus' name, amen.", prayer_type: 'people', person_name: 'Riley', prayed: true, prayer_count: 3, last_prayed_at: iso(daysAgo(referenceDate, 1)), status: 'pending', metadata: { ...active, original_request_id: id('request-recent'), original_request_content: 'Please pray for encouragement before a presentation.', prayer_updates: [{ id: `${id('request-recent-response')}-u1`, date: iso(daysAgo(referenceDate, 1)), text: 'The presentation moved to next week, so there is more time to prepare.', kind: 'situation-changed' }] }, createdDaysAgo: 20, updatedDaysAgo: 1 }),
    make({ id: id('let-go'), demoLabel: 'Let Go — released plan', expectedToday: 'remember', expectedReview: 'Dated Let Go event', content: 'A fictional plan I chose to release without forcing an outcome.', prayer_type: 'journal', journal_category: 'supplication', prayed: true, prayer_count: 3, status: 'pending', metadata: { track_answered: true, is_active: false, tracking_status: 'closed', lifecycle_history: [lifecycle('let-go', 14, 'let-go')] }, createdMonthsAgo: 3, updatedDaysAgo: 14 }),
    make({ id: id('answered-let-go'), demoLabel: 'Answered then Let Go', expectedToday: 'celebrate', expectedReview: 'Answer and dated Let Go', content: 'Thank You for the help received; I release the remaining outcome.', prayer_type: 'journal', journal_category: 'supplication', prayed: true, prayer_count: 5, status: 'answered', answered_date: iso(daysAgo(referenceDate, 40)), metadata: { track_answered: true, is_active: false, tracking_status: 'closed', answer_history: [answer('answered-let-go', 40, 'Timely help arrived.')], lifecycle_history: [lifecycle('answered-let-go', 10, 'let-go')] }, createdMonthsAgo: 5, updatedDaysAgo: 10 }),
    make({ id: id('legacy-closed'), demoLabel: 'Legacy closed without event date', expectedToday: 'remember', expectedReview: 'No fabricated Let Go event', content: 'A saved historical prayer without a dated closure event.', prayer_type: 'journal', journal_category: 'supplication', prayed: true, prayer_count: 2, status: 'pending', metadata: { track_answered: true, is_active: false, tracking_status: 'closed' }, createdMonthsAgo: 6, updatedDaysAgo: 60 }),
    ...(['confession', 'adoration', 'supplication', 'thanksgiving'] as const).map(category => make({ id: id(`cast-${category}`), demoLabel: `CAST — ${category}`, expectedToday: category === 'supplication' ? 'return' : category === 'thanksgiving' ? 'remember' : 'none', expectedReview: category === 'thanksgiving' ? 'Thanksgiving' : category === 'supplication' ? 'One CAST Prayer journey' : 'Not automatically surfaced', content: ({ confession: 'Father, forgive me for the way I responded out of frustration today. I was more concerned about being understood than listening well. Forgive the pride in my heart and help me respond with humility, patience, and grace.', adoration: 'Lord, You are patient, merciful, and slow to anger. You remain faithful even when my heart is restless. You are worthy of my trust because Your character does not change.', supplication: "Heavenly Father, please give me wisdom for the decisions I need to make this week. Help me recognize what is wise rather than simply what is easy. Give me courage to obey You even when the next step feels uncertain.\n\nIn Jesus' name, amen.", thanksgiving: 'Thank You, Lord, for providing what I needed this week, for the people who encouraged me, and for quiet moments that reminded me I am not carrying everything alone.' })[category], prayer_type: 'journal', journal_category: category, prayed: category === 'supplication', prayer_count: category === 'supplication' ? 3 : 0, last_prayed_at: category === 'supplication' ? iso(daysAgo(referenceDate, 15)) : undefined, status: 'pending', metadata: { ...(category === 'supplication' ? active : { track_answered: false, is_active: false }), prayer_style: 'cast', prayer_session_id: id('cast-session') }, createdDaysAgo: 30, updatedDaysAgo: category === 'supplication' ? 15 : 30 })),
    ...(['confession', 'adoration', 'supplication', 'thanksgiving'] as const).map(category => make({ id: id(`cast-two-${category}`), demoLabel: `CAST session two — ${category}`, expectedToday: 'none', expectedReview: category === 'thanksgiving' ? 'Thanksgiving' : 'CAST history', content: ({ confession: 'Lord, I confess that worry has made me impatient with the people around me. I have tried to manage every detail instead of trusting You. Please forgive me and teach me to be present, gentle, and honest.', adoration: 'God, You are wise beyond what I can understand and gracious in every season. Your attention is never divided, Your promises are dependable, and Your love is not fragile.', supplication: "Father, give me courage for the conversation ahead. Help me speak truth without harshness, listen without preparing a defense, and seek peace rather than simply trying to win.\n\nIn Jesus' name, amen.", thanksgiving: 'Father, thank You for strength to finish what needed to be done this week and for friends who noticed I was tired and checked on me. Thank You for ordinary kindness that arrived at the right time.' })[category], prayer_type: 'journal', journal_category: category, prayed: category === 'supplication', prayer_count: category === 'supplication' ? 2 : 0, last_prayed_at: category === 'supplication' ? iso(daysAgo(referenceDate, 45)) : undefined, status: 'pending', metadata: { ...(category === 'supplication' ? { ...active, is_active: false, tracking_status: 'closed', lifecycle_history: [lifecycle('cast-two', 20, 'let-go')] } : { track_answered: false, is_active: false }), prayer_style: 'cast', prayer_session_id: id('cast-session-two') }, createdMonthsAgo: 3, updatedDaysAgo: 20 })),
    make({ id: id('open-short'), demoLabel: 'Short Open Prayer', expectedToday: 'remember', expectedReview: 'Open Prayer history', content: "Dear Lord, give me peace about tomorrow and help me trust You with what I cannot control. Help me walk into the day with wisdom instead of fear.\n\nIn Jesus' name, amen.", prayer_type: 'journal', journal_category: 'personal_prayer', prayed: false, prayer_count: 0, status: 'pending', metadata: { prayer_style: 'open', track_answered: false, is_active: false }, createdDaysAgo: 8 }),
    make({ id: id('open-long'), demoLabel: 'Long Open Prayer', expectedToday: 'return', expectedReview: 'Still carrying', content: "Heavenly Father,\n\nThank You that I can come to You even when my thoughts feel scattered. I have been trying to understand what the next season should look like, and I keep moving between excitement and fear. Please help me not to rush simply because waiting is uncomfortable.\n\nGive me wisdom for the decisions in front of me. Show me where I need to be faithful with what I already have instead of constantly looking for the next answer. Give me courage for the conversations I need to have, humility when I am wrong, and patience when the outcome is not yet clear.\n\nMost of all, help me trust Your character more than I trust my ability to predict what will happen.\n\nIn Jesus' name, amen.", prayer_type: 'journal', journal_category: 'personal_prayer', prayed: true, prayer_count: 5, last_prayed_at: iso(daysAgo(referenceDate, 23)), status: 'pending', metadata: { ...active, prayer_style: 'open' }, createdMonthsAgo: 6, updatedDaysAgo: 23 }),
    make({ id: id('person-greg'), demoLabel: 'For Someone — Greg operation', expectedToday: 'return', expectedReview: 'Answered and still carrying', content: "Lord, I pray for Greg as he prepares for his operation. Please give him peace as he waits and guide the doctors, nurses, and everyone caring for him. Give them wisdom and steady hands. Strengthen Greg's body through recovery and give his family peace in the uncertainty.\n\nIn Jesus' name, amen.", prayer_type: 'people', person_name: 'Greg', prayed: true, prayer_count: 6, last_prayed_at: iso(daysAgo(referenceDate, 8)), status: 'answered', answered_date: iso(daysAgo(referenceDate, 10)), metadata: { ...active, answer_history: [answer('person-greg', 10, 'The operation went well and the doctors are pleased with the first stage of recovery.')], prayer_updates: [{ id: `${id('person-greg')}-u1`, date: iso(daysAgo(referenceDate, 8)), text: 'Recovery is still ongoing, so I want to continue praying for strength and rest.', kind: 'continue-praying' }] }, createdDaysAgo: 40, updatedDaysAgo: 8 }),
    make({ id: id('person-maya'), demoLabel: 'For Someone — Maya interview', expectedToday: 'celebrate', expectedReview: 'Answer event', content: "Heavenly Father, I pray for Maya as she prepares for her interview. Calm her nerves and help her communicate clearly and confidently. Give her wisdom in every answer and remind her that her worth is not determined by the outcome.\n\nIn Jesus' name, amen.", prayer_type: 'people', person_name: 'Maya', prayed: true, prayer_count: 3, last_prayed_at: iso(daysAgo(referenceDate, 12)), status: 'answered', answered_date: iso(daysAgo(referenceDate, 6)), metadata: { track_answered: true, is_active: false, tracking_status: 'answered', answer_history: [answer('person-maya', 6, 'Maya received an offer on Friday, and the schedule fits the responsibilities she had been concerned about.')] }, createdDaysAgo: 32, updatedDaysAgo: 6 }),
    make({ id: id('person-daniel'), demoLabel: 'For Someone — Daniel conversation', expectedToday: 'return', expectedReview: 'Still carrying', content: "Father, I pray for Daniel as he prepares for this difficult conversation. Help him speak truthfully without being harsh and listen without becoming defensive. Give him wisdom to know what needs to be said and what can wait. Please bring peace and humility into the conversation.\n\nIn Jesus' name, amen.", prayer_type: 'people', person_name: 'Daniel', prayed: true, prayer_count: 4, last_prayed_at: iso(daysAgo(referenceDate, 18)), status: 'pending', metadata: active, createdDaysAgo: 50, updatedDaysAgo: 18 }),
    make({ id: id('person-samuel'), demoLabel: 'For Someone — Samuel new city', expectedToday: 'return', expectedReview: 'Still carrying', content: "Dear Lord, I pray for Samuel as he settles into a new city. Give him peace in the unfamiliar parts of this transition and provide good people around him. Help him find a church community where he can grow, serve, and build real friendships.\n\nIn Jesus' name, amen.", prayer_type: 'people', person_name: 'Samuel Alexander', prayed: true, prayer_count: 2, last_prayed_at: iso(daysAgo(referenceDate, 11)), status: 'pending', metadata: active, createdDaysAgo: 28, updatedDaysAgo: 11 }),
    make({ id: id('request-charles'), demoLabel: 'Request — Charles exams', expectedToday: 'none', expectedReview: 'Original request journey context', content: "Please pray that I have wisdom, retention, and recall for my exams on Monday. I've been studying, but I've been anxious and having trouble sleeping.", prayer_type: 'people', person_name: 'Charles', requested_by: 'Charles', is_prayer_request: true, prayed: true, prayer_count: 1, status: 'pending', metadata: active, createdDaysAgo: 27 }),
    make({ id: id('request-charles-response'), demoLabel: 'Linked Prayer — Charles exams', expectedToday: 'follow_up', expectedReview: 'Request prayed for', content: "Father, I pray for my brother Charles as he prepares for his exams on Monday. Please calm his anxieties and help him rest well. Give him wisdom, understanding, retention, and clear recall of what he has studied. Remind him that his identity is not determined by a grade.\n\nIn Jesus' name, amen.", prayer_type: 'people', person_name: 'Charles', prayed: true, prayer_count: 2, last_prayed_at: iso(daysAgo(referenceDate, 19)), status: 'pending', metadata: { ...active, original_request_id: id('request-charles'), original_request_content: "Please pray that I have wisdom, retention, and recall for my exams on Monday. I've been studying, but I've been anxious and having trouble sleeping.", prayer_updates: [{ id: `${id('request-charles-response')}-u1`, date: iso(daysAgo(referenceDate, 12)), text: 'Charles finished the first exam and said it went better than he expected. He still has two more this week.', kind: 'continue-praying' }] }, createdDaysAgo: 25, updatedDaysAgo: 12 }),
    make({ id: id('request-rachel'), demoLabel: 'Request — Rachel interview', expectedToday: 'none', expectedReview: 'Original request journey context', content: "Please pray for my interview on Thursday. I really want this opportunity, but I also want to trust God if it isn't the right place for me.", prayer_type: 'people', person_name: 'Rachel', requested_by: 'Rachel', is_prayer_request: true, prayed: true, prayer_count: 1, status: 'pending', metadata: active, createdDaysAgo: 16 }),
    make({ id: id('request-rachel-response'), demoLabel: 'Linked Prayer — Rachel recent follow-up', expectedToday: 'none', expectedReview: 'Recent meaningful update', content: "Heavenly Father, I pray for Rachel as she prepares for her interview. Give her peace, clarity, and confidence as she speaks. Help her answer honestly and thoughtfully and trust You with what comes next.\n\nIn Jesus' name, amen.", prayer_type: 'people', person_name: 'Rachel', prayed: true, prayer_count: 2, last_prayed_at: iso(daysAgo(referenceDate, 5)), status: 'pending', metadata: { ...active, original_request_id: id('request-rachel'), original_request_content: "Please pray for my interview on Thursday. I really want this opportunity, but I also want to trust God if it isn't the right place for me.", prayer_updates: [{ id: `${id('request-rachel-response')}-u1`, date: iso(daysAgo(referenceDate, 1)), text: 'Rachel said the interview went well. She is waiting to hear back next week.', kind: 'situation-changed' }] }, createdDaysAgo: 15, updatedDaysAgo: 1 }),
    make({ id: id('request-leah'), demoLabel: 'Unprayed Request — Leah move', expectedToday: 'follow_up', expectedReview: 'Request received', content: "Please pray for peace as I prepare to move next month. I'm excited, but I'm also worried about leaving familiar people and starting again somewhere new.", prayer_type: 'people', person_name: 'Leah', requested_by: 'Leah', is_prayer_request: true, prayed: false, prayer_count: 0, status: 'pending', metadata: active, createdDaysAgo: 8 }),
    make({ id: id('request-marco'), demoLabel: 'Unprayed Request — Marco presentation', expectedToday: 'follow_up', expectedReview: 'Request received', content: 'Please pray for my presentation on Friday. I know the material, but I get very nervous speaking in front of senior leaders.', prayer_type: 'people', person_name: 'Marco', requested_by: 'Marco', is_prayer_request: true, prayed: false, prayer_count: 0, status: 'pending', metadata: active, createdDaysAgo: 2 }),
    make({ id: id('request-hannah'), demoLabel: 'Unprayed Request — Hannah family', expectedToday: 'follow_up', expectedReview: 'Request received', content: "Please pray for wisdom for our family. We need to make a decision soon, and we're not all seeing it the same way. We want to listen carefully and avoid making the decision out of pressure.", prayer_type: 'people', person_name: 'Hannah', requested_by: 'Hannah', is_prayer_request: true, prayed: false, prayer_count: 0, status: 'pending', metadata: active, createdDaysAgo: 1 }),
    ...([
      ['Provision', 'provision', 'Provision for the remaining community project expenses', 'Confirmation that the short-term contract would cover this month'],
      ['School', 'school', "Peace and clear recall during Charles's remaining exams", 'Acceptance into the professional training program'],
      ['Relationships', 'relationships', 'Patience and humility before talking with my sister', 'A calmer and more honest conversation with a close friend'],
      ['Work & business', 'work', 'Wisdom about whether to accept the new role', 'Confirmation of the project contract and start date'],
      ['Health', 'health', "Strength and steady recovery after Greg's operation", 'Clear follow-up test results with no additional procedure needed'],
      ['Guidance', 'guidance', 'Clarity about where to serve during this season', 'Peace about the next faithful step in the decision'],
      ['Other', 'other', 'Safe travel for the volunteer team next Friday', 'A safe place to stay during the trip'],
    ] as const).map(([topic, slug, activeText, answeredText], index) => make({ id: id(`needs-${slug}`), demoLabel: `Prayer Needs — ${topic}`, expectedToday: index === 0 ? 'return' : 'none', expectedReview: 'Answered Need plus Still Carrying', content: `${activeText}\n${answeredText}`, notes: `A coherent fictional ${topic.toLowerCase()} prayer journey with active and answered concerns.`, prayer_type: 'journal', journal_category: 'supplication', prayed: true, prayer_count: 2 + index, last_prayed_at: iso(daysAgo(referenceDate, 9 + index)), status: 'answered', metadata: { ...active, prayer_need: true, topics: [topic], prayer_needs: [need(`${slug}-active`, topic, activeText, 'active'), need(`${slug}-answered`, topic, answeredText, 'answered', 5 + index)] }, createdMonthsAgo: 2 + (index % 3), updatedDaysAgo: 5 + index })),
    make({ id: id('thanksgiving-old'), demoLabel: 'Thanksgiving history', expectedToday: 'remember', expectedReview: 'Quarterly/Yearly Thanksgiving', content: "Father, thank You for providing through an unexpected project this month. Thank You for reminding me that I don't have to know the entire path before taking the next faithful step.", prayer_type: 'journal', journal_category: 'thanksgiving', prayed: false, prayer_count: 0, status: 'pending', metadata: { track_answered: false, is_active: false }, createdMonthsAgo: 4, updatedDaysAgo: 90 }),
    make({ id: id('bible-study'), demoLabel: 'Bible Study Prayer — James 1', expectedToday: 'remember', expectedReview: 'Bible Study-origin Prayer', content: "Father, when I face trials, help me ask You for wisdom instead of immediately depending on my own understanding. Teach me to trust Your character when I cannot see what You are doing and help me become steadfast rather than double-minded.\n\nIn Jesus' name, amen.", prayer_type: 'journal', journal_category: 'supplication', prayed: false, prayer_count: 0, status: 'pending', metadata: { source: 'bible_study', bibleStudySessionId: id('bible-study-session'), bibleStudyReflectionId: id('bible-study-reflection'), passage: 'James 1:2–8', track_answered: false, is_active: false }, createdDaysAgo: 38, updatedDaysAgo: 38 }),
    make({ id: id('playbook'), demoLabel: 'Playbook-origin Prayer', expectedToday: 'remember', expectedReview: 'Compatibility-origin Prayer', content: "Father, help me follow through on the step I know I need to take. Give me courage to have the conversation with humility and clarity. Keep me from putting it off simply because I am uncomfortable, and help me leave the outcome in Your hands.\n\nIn Jesus' name, amen.", prayer_type: 'guided_playbook', title: 'A Courageous Conversation', prayed: false, prayer_count: 0, status: 'pending', metadata: { origin: 'playbook', source: 'playbook', playbook_id: id('playbook-source'), playbook_title: 'A Courageous Conversation', step_id: id('playbook-step'), subtask_id: id('playbook-subtask'), action_step_number: 2, action_step_title: 'Prepare to listen well', track_answered: false, is_active: false }, createdDaysAgo: 55, updatedDaysAgo: 55 }),
    make({ id: id('devotional'), demoLabel: 'Devotional-origin Prayer', expectedToday: 'remember', expectedReview: 'Compatibility-origin Prayer', content: "Lord, thank You that Your faithfulness is not dependent on my circumstances. Help me remember what I read today and respond to Your Word with obedience, not just agreement. Show me where I need to trust You more deeply this week.\n\nIn Jesus' name, amen.", prayer_type: 'devotional', title: 'Faithful in Every Season', day_number: 4, day_title: 'Trusting What Does Not Change', total_days: 7, prayed: false, prayer_count: 0, status: 'pending', metadata: { source: 'devotional', devotional_id: id('devotional-source'), devotional_title: 'Faithful in Every Season', track_answered: false, is_active: false }, createdDaysAgo: 42, updatedDaysAgo: 42 }),
  ];
}

const scenarioIds: Record<PrayerV2DemoScenario, string[]> = {
  full: [], review: [],
  cast: ['confession', 'adoration', 'supplication', 'thanksgiving'].map(name => id(`cast-${name}`)),
  return: [id('return'), id('recent-active')],
  check_in: [id('return'), id('check-in'), id('old-recent')],
  follow_up: [id('request-unprayed'), id('request-prayed'), id('request-prayed-response'), id('request-recent'), id('request-recent-response')],
  remember: [id('remember')], celebrate: [id('one-answer')], mixed_needs: [id('mixed-needs')],
};

export function fixturesForScenario(scenario: PrayerV2DemoScenario, referenceDate: Date) {
  const all = buildPrayerV2DemoFixtures(referenceDate);
  return scenario === 'full' || scenario === 'review' ? all : all.filter(item => scenarioIds[scenario].includes(item.id));
}
